export const ORDER_STATUS = Object.freeze({
  DRAFT: "draft",
  PENDING_PAYMENT: "pending_payment",
  COD_PENDING_APPROVAL: "cod_pending_approval",
  PAYMENT_RECEIVED: "payment_received",
  STOCK_CONFIRMED: "stock_confirmed",
  PAID_LEGACY: "paid",
  FULFILLED: "fulfilled",
  CANCELLED: "cancelled",
  PARTIALLY_REFUNDED: "partially_refunded",
  REFUNDED: "refunded",
});

export const ORDER_TRANSITIONS = Object.freeze({
  [ORDER_STATUS.DRAFT]: [ORDER_STATUS.PENDING_PAYMENT, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PENDING_PAYMENT]: [ORDER_STATUS.PAYMENT_RECEIVED, ORDER_STATUS.COD_PENDING_APPROVAL, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.COD_PENDING_APPROVAL]: [ORDER_STATUS.PENDING_PAYMENT, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PAYMENT_RECEIVED]: [
    ORDER_STATUS.STOCK_CONFIRMED,
    ORDER_STATUS.CANCELLED,
    ORDER_STATUS.PARTIALLY_REFUNDED,
    ORDER_STATUS.REFUNDED,
  ],
  [ORDER_STATUS.STOCK_CONFIRMED]: [
    ORDER_STATUS.FULFILLED,
    ORDER_STATUS.PARTIALLY_REFUNDED,
    ORDER_STATUS.REFUNDED,
  ],
  [ORDER_STATUS.PAID_LEGACY]: [ORDER_STATUS.STOCK_CONFIRMED, ORDER_STATUS.PARTIALLY_REFUNDED, ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.FULFILLED]: [ORDER_STATUS.PARTIALLY_REFUNDED, ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.PARTIALLY_REFUNDED]: [ORDER_STATUS.REFUNDED],
  [ORDER_STATUS.CANCELLED]: [],
  [ORDER_STATUS.REFUNDED]: [],
});

export const ORDER_REFUND_STATUSES = Object.freeze([
  ORDER_STATUS.PARTIALLY_REFUNDED,
  ORDER_STATUS.REFUNDED,
]);

export const ORDER_SYSTEM_MANAGED_STATUSES = Object.freeze([
  ORDER_STATUS.PAYMENT_RECEIVED,
  ORDER_STATUS.PAID_LEGACY,
]);

export function assertOrderTransition(from, to) {
  if (from === to) return true;
  const allowed = ORDER_TRANSITIONS[from] || [];
  if (!allowed.includes(to)) {
    const err = new Error("ORDER_STATE_INVALID_TRANSITION");
    err.statusCode = 409;
    err.code = "ORDER_STATE_INVALID_TRANSITION";
    err.details = { from, to };
    throw err;
  }
  return true;
}
